const actionTypes = {
  LOGIN: 'LOGIN',
  FETCH_REQUEST_TOKEN: 'FETCH_REQUEST_TOKEN',
  FETCH_REQUEST_QUESTION: 'FETCH_REQUEST_QUESTION',
  FETCH_SUCCESS_TOKEN: 'FETCH_SUCCESS_TOKEN',
  FETCH_SUCCESS_QUESTIONS: 'FETCH_SUCCESS_QUESTIONS',
  FETCH_FAILURE: 'FETCH_FAILURE',
  TIMER_DECREASING: 'TIMER_DECREASING',
  TIMER_RESET: 'TIMER_RESET',
  SCORE_UPDATE: 'SCORE_UPDATE',
};

export default actionTypes;
